#include "FragTrap.hpp"
#include "ScavTrap.hpp"

int main(void)
{
    FragTrap ab;
    FragTrap ba("Lou");
    FragTrap ca;
    FragTrap ac("Rodrigo");
    ca = ac;

    ba.attack("bobby");

    std::cout << "Copy of ac to ca :" << std::endl;
    ca.highFivesGuys(); 
    std::cout << "ab test highFives > energy == 0 :" << std::endl;
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    ab.highFivesGuys();
    std::cout << "ac test repaired : " << std::endl;
    ac.beRepaired(30);




}